model: &retrieval_gpt2
    type: gpt2
    n_positions: 300
    n_layer: 4
    n_embd: 64
    n_head: 2

optim:
    type: adam
    lr: 0.0004
loss_fn:
    type: squared
function_class: 
    type: retrieval
b_size: 64
seq_len: 140
x_dim: 10
x_dist:
    type: retrieval
steps: 500001
log_freq: 10
checkpoint_freq: 50000
model: *retrieval_gpt2
# baseline_models: [*least_squares, *knn_3, *averaging]