optim:
    type: adam
    lr: 0.0004
loss_fn:
    type: squared
function_class: 
    type: sparse parity regression
    k: 2
b_size: 64
seq_len: 140
x_dim: 10
x_dist:
    type: sparse
steps: 500001
log_freq: 100
checkpoint_freq: 50000
model: *modified_gpt2
baseline_models: [*least_squares, *knn_3, *averaging]