function_class: 
    type: chebyshev kernel linear regression
steps: 1000000
log_freq: 2000
checkpoint_freq: 2000
optim:
    type: adam
    lr: 0.00005
loss_fn:
    type: mse
b_size: 64
seq_len: 31
x_dim: 1
x_dist:
    type: uniform
model: *soft_prompting_std_gpt2
    prompt_pairs: 50