function_class: 
    type: chebyshev kernel linear regression
steps: 1000000
log_freq: 100
checkpoint_freq: 1000
optim:
    type: adam
    lr: 0.00005
loss_fn:
    type: mse
b_size: 64
seq_len: 31
x_dim: 1
x_dist:
    type: uniform
model: *soft_prompting_std_gpt2
    prompt_pairs: 50
baseline_models: 
    - <<: *knn_3
    - <<: *xgboost
    - <<: *decision_tree
    - <<: *decision_tree_4
    - <<: *least_squares
    - <<: *averaging
    - <<: *mlp
    - <<: *lasso
      alpha: 0.001