function_class: 
    type: chebyshev kernel linear regression
    lowest_degree: 0
    highest_degree: 11
    fixed_linear_coefficients: 0
    different_degrees: True
steps: 3002000
log_freq: 2000
checkpoint_freq: 20000
optim:
    type: adam
    lr: 0.00005
loss_fn:
    type: mse
b_size: 64
seq_len: !curriculum
    start: 5
    stop: 81
    step_size: 2
    step_len: 2000
x_dim: 1
x_dist:
    type: uniform
model: *std_gpt2_poly_paper