name: pyright-type-checking

on:
    pull_request:
        branches: [main]

jobs:
    type-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Miniconda
              uses: conda-incubator/setup-miniconda@v3.0.3
              with:
                  # Specific version of Conda to install after miniconda is located 
                  #    or installed. See https://anaconda.org/anaconda/conda for 
                  #    available "conda" versions.
                  # conda-version: # something, this may be useful later
                  # Environment.yml to create an environment.
                  # environment-file: environment.yaml
                  # Environment name (or path) to activate on all shells. Default 
                  #    is `test` which will be created in `$CONDA/envs/test`. If the 
                  #    environment does not exist, it will be created and activated. 
                  #    If `environment-file` is used and you want that to be the 
                  #    environment used, you need to explicitely provide the name of 
                  #    that environment on `activate-environment`.
                  activate-environment: in-context-learning
                  # Exact version of a Python version to use on "activate-environment". 
                  #    If provided, this will be installed before the "environment-file". 
                  #    See https://anaconda.org/anaconda/python for available "python" versions.
                  python-version: ${{ matrix.python-version }}

            - name: Load cached env
              uses: actions/cache/restore@v4
              id: cache-miniconda-load
              with:
                  path: /usr/share/miniconda/envs/in-context-learning
                  key: ${{ runner.os }}-${{ hashFiles('environment.yaml') }}

            - name: Update the conda env
              if: steps.cache-miniconda-load.outputs.cache-hit != 'true'
              run: conda env update -n in-context-learning -f environment.yaml

            - name: Write env to cache
              id: cache-miniconda-save
              uses: actions/cache/save@v4
              with:
                  path: /usr/share/miniconda/envs/in-context-learning
                  key: ${{ steps.cache-miniconda-load.outputs.cache-primary-key }}

            - name: Run PyRight with PyLance version
              uses: jakebailey/pyright-action@v2
              with:
                  pylance-version: latest-release
                  python-path: /usr/share/miniconda/envs/in-context-learning/bin/python
