name: pyright-type-checking

on:
    pull_request:
        branches: [main]

jobs:
    conda:
        uses: ./.github/workflows/conda_cache.yml

    type-check:
        needs: conda
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v4

            - name: Run PyRight with PyLance version
              uses: jakebailey/pyright-action@v2
              with:
                  pylance-version: latest-release
                  python-path: /usr/share/miniconda/envs/in-context-learning/bin/python
