name: pyright-type-checking

on:
    pull_request:
        branches: [main]

jobs:
    type-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: ./.github/workflows/conda_cache.yml

            - name: Run PyRight with PyLance version
              uses: jakebailey/pyright-action@v2
              with:
                  pylance-version: latest-release
                  python-path: /usr/share/miniconda/envs/in-context-learning/bin/python
