name: test-function-classes

on:
    pull_request:
        branches: [main]

jobs:
    conda:
        uses: ./.github/workflows/conda_cache.yml

    test:
        needs: conda
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v4

            - name: Test function classes
              run: source .github/checks.sh && run_func_checks
